
project_id = "qjgbmowupuzgwrfcmaao"

[functions.make-call]
verify_jwt = true

[functions.send-message]
verify_jwt = true

[functions.handle-webhooks]
verify_jwt = false

[functions.get-twilio-token]
verify_jwt = true
