// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjgbmowupuzgwrfcmaao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqZ2Jtb3d1cHV6Z3dyZmNtYWFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTQyNjAsImV4cCI6MjA1OTk3MDI2MH0.7MM5nu9Okyi2GcqIYmsSrvps0qRhF3xDMt1UExq7SWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);